- name: Create sudoers file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/somegroup"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"

- name: install utility packages (apt)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - vim
    - pigz
    - lvm2
    - xfsprogs
    - sysstat
    - pv
    - wget
    - htop
    - iftop
    - nfs-common
    - tmux
    - curl
    - python
